package com.casemanagement.system.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestMethod;
import com.casemanagement.system.model.CaseType;
import com.casemanagement.system.model.CaseTypeRepository;
import com.casemanagement.system.model.ClientCase;
import com.casemanagement.system.model.ClientCaseRepository;
import com.casemanagement.system.model.ClientRepository;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@Controller
// @ResponseBody
public class CaseController {

  @Autowired
  private ClientCaseRepository clientcaseRepos;

  @Autowired
  private CaseTypeRepository casetypeRepos; // this repository is showing the tyep of the case;

  @Autowired
  private ClientRepository clientRepos;

  // @Controller
  // public class HomeController {
  //   @GetMapping("/")
  //   public String home() {
  //     return "Hello, you are logged in!";
  //   }
  // }

  @RequestMapping("/login")
  public String loginmethod() {
      return "login";
  }
  

  @RequestMapping("/caselist")
  public String firstMethod(Model model) {

    model.addAttribute("clientcaseRepo", clientcaseRepos.findAll());
    model.addAttribute("clientRepos", clientRepos.findAll()); // adding this for testing without using constructor in
                                                              // clientcase.
    return "caseList";
  }

  // need to look into this
  @GetMapping("/case/{caseNumber}/clients")
  public String showClientsByCase(@PathVariable String caseNumber, Model model) {
    ClientCase clientCase = clientcaseRepos.findByCaseNumber(caseNumber);
    model.addAttribute("case", clientCase);
    model.addAttribute("clients", clientCase.getClients());
    return "clientdetails";
  }

  // adding a case
  @GetMapping("/addcase")
  public String addACase(Model model) {
    model.addAttribute("addcasevari", new ClientCase());
    model.addAttribute("typevariables", casetypeRepos.findAll());
    return "addcase";
  }

  // edit a case
  // here we use case id generated by the database to edit since it is more safer
  // than using the case number but for deleteing we use a custom method to delete
  // the case.
  @RequestMapping(value = "/edit/{id}")
  public String editACase(@PathVariable("id") Long caseId, Model model) {
    model.addAttribute("caseVariable", clientcaseRepos.findById(caseId));
    model.addAttribute("typeVaribales", casetypeRepos.findAll()); // we add type because when editing we might need to
                                                                  // change the case type too.
    return "editcase";
  }

  // save a case
  @PostMapping("/save")
  public String SaveACase(ClientCase clientcase) {

    if (clientcase.getType() != null && clientcase.getType().getTypeid() != null) {
      Long typeId = clientcase.getType().getTypeid();
      clientcase.setType(casetypeRepos.findById(typeId).orElse(null));
    }

    clientcaseRepos.save(clientcase);
    return "redirect:/caselist";
  }

  // delete a case
  // here a custom method to delete the case is added to clientCaseRepository to
  // delete a case by it's case number.
  @RequestMapping(value = "/deletebyname/{caseNumber}", method = RequestMethod.GET)
  @PreAuthorize("hasRole('ADMIN')")
  public String deleteCase(@PathVariable("caseNumber") String caseNumber, Model model) {
    clientcaseRepos.deleteByCaseNumber(caseNumber);
    return "redirect:/caselist";
  }

  @PostMapping("/updateDate")
  public String updateCourtDate(ClientCase updatedCase) {
    ClientCase existingCase = clientcaseRepos.findById(updatedCase.getCaseId())
        .orElseThrow(() -> new IllegalArgumentException("Invalid case ID: " +
            updatedCase.getCaseId()));

    existingCase.setCourtDate(updatedCase.getCourtDate()); // only update the date

    clientcaseRepos.save(existingCase);

    return "redirect:/caselist";
  }

}
